Feture/switchrole
kamilnapiontek/tournamentMaker pull request #7
Opened 2023-05-30 19:12 UTC by kamilnapiontek

2023-05-30 22:24 UTC, Y0ucandev requested changes

2023-05-30 22:24 UTC, Y0ucandev commented on src/main/java/com/example/tournamentMaker/Controller.java
> +}
do wyrzucenia ten plik

2023-05-30 22:24 UTC, Y0ucandev commented on src/main/java/com/example/tournamentMaker/security/auth/AuthenticationController.java
> +    ) {
formatowanie. Sprawdz na kazdym pliku bo tu cos dziwnie te nawiasy sa przeniesione

2023-05-30 22:24 UTC, Y0ucandev commented on src/main/java/com/example/tournamentMaker/security/auth/AuthenticationRequest.java
> +    String password;
czemu to nie jest prywatne i usunales getter?

2023-05-30 22:24 UTC, Y0ucandev commented on src/main/java/com/example/tournamentMaker/security/auth/AuthenticationService.java
> +        );
nie pieka cie oczy ?

2023-05-30 22:24 UTC, Y0ucandev commented on src/main/java/com/example/tournamentMaker/security/auth/RegisterRequest.java
>  public class RegisterRequest {
ogarnij wszystkie miejsca gdzie jest uzywany builder i inne konstruktory. CHcialbym aby byl uzywany tylko builder lub tlyko konstruktory

2023-05-30 22:24 UTC, Y0ucandev commented on src/main/java/com/example/tournamentMaker/security/config/SecurityConfiguration.java
> +                        "/swagger-ui.html"
polowy z tych urli to ty nie uzywasz. Wiesz o tym ? czy tka po prostu na chama wszystko wkopiowales i nawet nie wiesz co masz w kodzie ?

2023-05-31 01:06 UTC, kamilnapiontek commented on src/main/java/com/example/tournamentMaker/security/config/SecurityConfiguration.java
> +                        "/swagger-ui.html"
Nie do końca rozumiałem czemu tu są, więc je zostawiłem, że to whitelista to tyle wiem

2023-05-31 09:35 UTC, Y0ucandev commented on src/main/java/com/example/tournamentMaker/security/config/SecurityConfiguration.java
> +                        "/swagger-ui.html"
zostaw tu tylko to co jest Twoim urlem

2023-05-31 11:06 UTC, kamilnapiontek commented
Poprawiłem już, nie widać nowego PR?Wiadomość napisana przez Y0ucandev ***@***.***> w dniu 31.05.2023, o godz. 11:35:﻿
@Y0ucandev commented on this pull request.



In src/main/java/com/example/tournamentMaker/security/config/SecurityConfiguration.java:
> +                        "/api/v1/auth/**",
+                        "/v2/api-docs",
+                        "/v3/api-docs",
+                        "/v3/api-docs/**",
+                        "/swagger-resources",
+                        "/swagger-resources/**",
+                        "/configuration/ui",
+                        "/configuration/security",
+                        "/swagger-ui/**",
+                        "/webjars/**",
+                        "/swagger-ui.html"

zostaw tu tylko to co jest Twoim urlem

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-06-04 17:51 UTC, merged